algoritmo "conteate10"
var
    contador, salto, valor: inteiro
inicio
    contador <- 0
        escreva("Quer contar até quanto? ")
            leia(valor)
                escreval(valor)
        Escreva("qual sera o valor do salto? ")
            leia(salto)
                escreval(salto)
        enquanto (contador <= valor) faca
            escreval(contador)
            contador <- contador + salto
        fimenquanto
        escreval("terminei de contar")
fimalgoritmo