algoritmo "somadorNumerico"

var
N, S: Inteiro
resp: caractere

inicio
 S <-0
 resp <- "S"
    Enquanto (resp = "S") faca
        Escreva ("Digite o valor => ")
            leia(N)
                escreval(n)
        S <- S + N
        Escreva ("Voce quer continuar? [S/N] ")      
            leia(resp)
                escreval(resp)
    fimenquanto
    escreval("A soma de todos os valores digitados é ", S)
fimalgoritmo