algoritmo "Nome do Programa"

var
    n, c, totN: Inteiro

inicio
    C <- 1
    TotN<- 0
    Repita
        escreva("Digite um número: ")
        Leia(N)
            se(N<0) entao
                TotN<- TotN + 1
            fimse
        escreval(N)
        c<- c+1
    ate(C>5)

    escolha totn
    caso 0
        EscrevaL("não ouve números negativos")
    outrocaso
        EscrevaL("Foram digitados ", totN, "valores negativos")
    fimescolha


fimalgoritmo