algoritmo "Fatorial"

var
    C, N, F: Inteiro
    R: caractere
inicio

repita
    Escreva("Que número quer que seja fatorado? ")
    leia(N)
        escreval(N)
    C <- N 
    F <- 1
    Repita
        Escreval(C, "x", 1)
        F <- F* C
        c<- c- 1
    ate (c<1)
    escrevaL ("o valor fatorial de ", N, " é igual a ", f)
    escreva("Quer Continuar? [S/N]")
    leia(R)
    limpatela
    Ate (R = "N")
fimalgoritmo