algoritmo "SomaFuncao"

var
    v1, v2, S: inteiro

Funcao Soma(X, Y: inteiro): inteiro
inicio
    retorne x + y
fimfuncao

inicio
    Escreva("Digite o primeiro valor: ")
        leia(V1)
            escreval(V1)
    escreval("digite o segundo valor: ")
        leia(V2)
            escreval(V2)
        S <- Soma(V1, V2)
    
    escreval("A soma entre ", V1, " e ", V2, " é igual a ", S)
fimalgoritmo