algoritmo "Lermatriz"

var
    mat: vetor[1..3, 1..2] de Inteiro
    l, c: inteiro
inicio
    Para l de 1 ate 3 faca
        para c de 1 ate 2 faca
            escreva("Digite um valor da posição [", l, ",", c, "]: ")
                Leia(Mat[l,c])
                    escreval(Mat[l,c])
        FimPara
    FimPara

        para l de 1 ate 3 faca
            para c de 1 ate 2 faca
                escreva(Mat[l,c]:5)
            fimpara
            escreval()
        fimpara
fimalgoritmo